Vdat burst combination
JulietGroundwater/Groundwater pull request #12
Opened 2019-02-08 18:02 UTC by ChrisBaish

2019-02-09 20:08 UTC, tapfm submitted a review, later dismissed
Code looks good, will have to look at using jUnit or similar for testing soon

2019-02-11 13:47 UTC, tapfm requested changes
Please fix the returning of lists, so that it is a clone and it is return a List<> in all instances rather than a ArrayList<>. It may be worth considering making lots of the variables immutable anyway.

Additionally please remove ComputationEngineTest.java from the repository.

Apart from that the code seems good.

2019-02-11 13:47 UTC, tapfm commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +    public ArrayList<Double> getAttenuator1() {
Should return List<Double> rather than ArrayList<Double>

2019-02-11 13:47 UTC, tapfm commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        return attenuator1;
Should return a clone of the list eg. return new ArrayList<>(attenuator1);

2019-02-11 13:47 UTC, tapfm commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        return attenuator2;
Similar to attenuator1

2019-02-11 13:47 UTC, tapfm commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        return TxAnt;
Similar to attenuator1

2019-02-11 13:47 UTC, tapfm commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        return RxAnt;
Similar to attenuator1

2019-02-11 13:47 UTC, tapfm commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        return v;
Should return a clone of v, not just a reference to it

2019-02-11 13:47 UTC, tapfm commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        return startInd;
Return a clone

2019-02-11 13:47 UTC, tapfm commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        return endInd;
return a clone

2019-02-12 16:54 UTC, enchom commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        int[] searchCR = strFind(mainString.substring(searchInd[0]), "\r\n");
Are you sure this is fine and not windows-specific?

2019-02-12 17:10 UTC, enchom commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +    private ArrayList<Double> attenuator1;
Replace all ArrayList with List in field definitions.

2019-02-12 17:10 UTC, enchom commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +    private ArrayList<Integer> parseIntArray(String mainString, String searchString) {
Replace all ArrayList with List in function return types

2019-02-12 20:02 UTC, tapfm approved these changes

2019-02-12 22:46 UTC, ChrisBaish commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        int[] searchCR = strFind(mainString.substring(searchInd[0]), "\r\n");
This is an exact copy of the Matlab. I'm on Linux and it works for me.

2019-02-12 22:47 UTC, ChrisBaish commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +    private ArrayList<Integer> parseIntArray(String mainString, String searchString) {
For private functions this removes a large amount of casting.

2019-02-12 22:47 UTC, ChrisBaish commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +    private ArrayList<Double> attenuator1;
Already merged in, but can be added to a future PR

2019-02-12 23:41 UTC, enchom commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +        int[] searchCR = strFind(mainString.substring(searchInd[0]), "\r\n");
Okay, I will take your word for it.

2019-02-12 23:41 UTC, enchom commented on computationEngine/src/main/java/uk/ac/cam/cl/juliet/computationengine/Burst.java
> +    private ArrayList<Integer> parseIntArray(String mainString, String searchString) {
There shouldn't be any casting at all if everything is a List?

2019-02-13 09:35 UTC, merged